### ISSUE TITLE
Comments within strings cause errors

### ISSUE THREAD

**Issue by benkasminbullock** [rjray/json-withcomments#2]
The module doesn't handle things that look like comments within strings:

```
use JSON::WithComments;
use JSON::Parse 'validate_json';
my $json =<<EOF;
{
"/* comment */":"/* not comment */",
"value":["//not comment"]
}
EOF
validate_json ($json);
my $jwc = JSON::WithComments->new;
my $hashref = $jwc->decode($json);
```
The `validate_json` is here just to check that the input is valid.

Incidentally if you want a module which strips C-style comments without removing them from strings, my module C::Tokenize offers this.
```
use C::Tokenize 'strip_comments';
my $json =<<EOF;
{
"/* comment */":"/* not comment */",
"value":["//not comment"]
}
EOF
print strip_comments ($json);
```

**Comment by rjray** [comment]
Actually, I support this by allowing for \\-escaping (my regex will not strip any comment where the leading / is preceded by a \\ character). I just forgot to put that in the docs, nor did I have any tests for it.

I have tests now, and guess what? JavaScript comments are working fine, but Perl-style comments lose the "#" character. Apparently, JSON is _extremely_ strict about the \\ character, and if you escape something other than the 8 or so characters they list in the spec, the \\ and the escaped character both disappear.

I can get around this by using the `relaxed` method when handling Perl comments (instead of the regexp approach). But that also makes a slight change to the parsing of the JSON itself, so I didn't want to take that route. I'll have to play with it a bit to see what I can do.

**Comment by rjray** [comment]
In fact, scratch what I said about the "invalid" escapes being deleted. That was a bug in my test script. In fact, such escapes cause an exception to be thrown. So `relaxed` it is...

**Comment by rjray** [comment]
I've just uploaded 0.003, which has much better documentation on how to accommodate JS-style comments in strings. It also has some basic tests. I opted not to use your module (though I tested it and it worked fine), because I want to maintain the behavior of replacing the removed comments with an equal number of spaces, which allows any parsing errors that occur to have accurate character offsets in the message.
